= Run Zephyr Samples

Zephyr には、いわゆる サンプルアプリケーションが数多く用意されています。Zephyr のドキュメントには、*Samples and Demos* という専用ページがあります。
このセクションでは、Zephyr のサンプルをいくつかビルドし、お使いの SC-OBC Module A1 で実行します。

Samples and Demos ページでは、サンプルを対話的に検索できます。Zephyr v4.1 には 500 を超えるサンプルがあります。
各サンプルの `README.rst` を一つずつ確認するより、Web インターフェースを使うほうがはるかに簡単です。

まだワークスペースを作成していない場合は、前のセクションに戻って作成してください。
このセクションでは、開発環境のセットアップがすでに完了しており、先に進める状態であることを前提とします。

== Blinky サンプル

最初のサンプルは *Blinky* です。このアプリケーションは Development Board 上の LED を点滅させます。

CAUTION: *Blinky* サンプルでは、SW1[10] (LED control) が ON になっていることを確認してください。
OFF になっている場合、LED は点滅しません。

=== ビルド

[source, console]
----
cd ~/myproject
source .venv/bin/activate
west build -p always -b scobc_a1 --shield scobc_a1_dev zephyr/samples/basic/blinky
----

これで最初のアプリケーションである Blinky がビルドされます。

これらの手順は、Zephyr ドキュメントの *Build the Blinky Sample* セクションと一致しています。

=== 書き込み

次に、SC-OBC Module A1 に書き込みます。

[source, console]
----
west flash
----

=== 確認

書き込み後、SC-OBC Module A1 の電源を入れ直してください。点滅する LED (_LED11_) が見えるはずです。

== Hello World サンプル

次は定番の *Hello World* サンプルです。Hello World を実行する前に、モジュールが PC に出力を送れるよう、シリアル接続を設定する必要があります。

=== コンソールを開く

SC-OBC Module A1 と PC の間をケーブルで接続し、端末でコンソールを開いてください。

[source, console]
----
tio /dev/ttyUSB2
----

CAUTION: Zephyr コンソールを使用するには、DIP スイッチ (_SW1_) の bit3 (RX) と bit4 (TX) を ON にする必要があります。現在 OFF の場合は、ON に切り替えてください。

=== ビルド

次に、別の端末を開いてサンプルをビルドします。

[source, console]
----
cd ~/myproject
source .venv/bin/activate
west build -p always -b scobc_a1 --shield scobc_a1_dev zephyr/samples/hello_world
----

=== 書き込み

次に、SC-OBC Module A1 に書き込みます。

[source, console]
----
west flash
----

=== 確認
SC-OBC Module A1 の電源を入れ直すと、シリアルコンソールに Hello World の文字列が表示されるはずです。
`tio` コンソールを終了したい場合は、まず `Ctrl + t` を押し、その後 `q` を押してください。
