= Run Zephyr Samples

Zephyr provides many so-called *sample applications*. The Zephyr documentation has a dedicated page called *Samples and Demos*.
In this section, we'll build a few samples from Zephyr and run them on your SC-OBC Module A1.

On the Samples and Demos page, you can interactively search samples. There are over 500 samples in Zephyr v4.1.
Using the web interface is much easier than checking each sample's README.rst.

If you haven't created your workspace yet, go back to the previous section and do so.
In this section, we assume you have already set up your development environment and are ready to proceed.

== Blinky sample
The first sample is *Blinky*. This application blinks an LED on your Development Board.

CAUTION: For the *Blinky* sample, make sure that SW1[10] (LED control) is turned ON.
If it is OFF, the LED will not blink.

=== Build

[source, console]
----
cd ~/myproject
python3 -m venv ~/zephyrproject/.venv
west build -p always -b scobc_a1 --shield scobc_a1_dev zephyr/samples/basic/blinky
----

This should build your first application, Blinky.

These steps match the *Build the Blinky Sample* section in the Zephyr documentation.

=== Flash

Next, we'll flash the SC-OBC Module A1:

[source, console]
----
west flash
----

=== Confirm
After flashing, power-cycle the SC-OBC Module A1. You should see the blinking LED (_LED11_).

== Hello World sample
Next is the ever-popular *Hello World* sample. Before running Hello World, we need to set up the serial connection so the module can send output to your PC.

=== Open Console

Connect the cable between your SC-OBC Module A1 and your PC, then open the console on terminal:

[source, console]
----
tio /dev/ttyUSB2
----

CAUTION: To use the Zephyr console, bit3 (RX) and bit4 (TX) of DIP Switch (_SW1_) must be turned ON. If they are currently OFF, please switch them ON.

=== Build

Then open the another terminal, and build the sample.

[source, console]
----
cd ~/myproject
python3 -m venv ~/zephyrproject/.venv
west build -p always -b scobc_a1 --shield scobc_a1_dev zephyr/samples/hello_world
----

=== Flash

Next, we'll flash the SC-OBC Module A1:

[source, console]
----
west flash
----

=== Confirm
After power-cycle the SC-OBC Module A1, you should see the Hello World string on your serial console.
If you want to exit the tio console, first press `Ctrl + t`, followed by `q`.
